GET http://localhost:5000/api/update-elo/wens-890


GET http://localhost:5000/api/update-elo/matw-444
GET http://localhost:5000/api/update-elo/cwax-450
GET http://localhost:5000/api/update-elo/bob-283

GET http://localhost:5000/api/getuser/cwax-450

GET http://localhost:5000/api/getuser/wens-890
GET http://localhost:5000/api/getuser/erer-100



GET http://localhost:5000/api/update-elo/matw-444

GET http://localhost:5000/api/user-ranks?player=wens-890
GET http://localhost:5000/api/user-ranks?player=cwax-450
GET http://localhost:5000/api/user-ranks?player=matw-444
