"""empty message

Revision ID: 0083d2491118
Revises: 733a57b4e97f
Create Date: 2024-03-29 12:27:17.570381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0083d2491118'
down_revision = '733a57b4e97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Continent', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('GlobalRank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('RegionalRank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('RegionalRank')
        batch_op.drop_column('GlobalRank')
        batch_op.drop_column('Continent')

    # ### end Alembic commands ###
