"""empty message

Revision ID: 194353fba644
Revises: 3f2fb2e023a8
Create Date: 2024-03-14 12:39:06.471559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194353fba644'
down_revision = '3f2fb2e023a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('LastUpdate',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_Users_LastUpdate'), ['LastUpdate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_LastUpdate'))
        batch_op.alter_column('LastUpdate',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
