"""empty message

Revision ID: 3f2fb2e023a8
Revises: 
Create Date: 2024-03-13 18:40:19.388522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2fb2e023a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('LastUpdate', sa.DateTime(), nullable=True),
    sa.Column('DisplayName', sa.String(length=16), nullable=False),
    sa.Column('ConnectCode', sa.String(length=9), nullable=False),
    sa.Column('CurrentRank', sa.Float(), nullable=False),
    sa.Column('UpdateCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_ConnectCode'), ['ConnectCode'], unique=True)

    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('UpdateCount', sa.Integer(), nullable=False),
    sa.Column('Rank', sa.FLOAT(), nullable=False),
    sa.Column('WinCount', sa.Integer(), nullable=True),
    sa.Column('LossCount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Transactions_Timestamp'), ['Timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Transactions_Timestamp'))

    op.drop_table('Transactions')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_ConnectCode'))

    op.drop_table('Users')
    # ### end Alembic commands ###
