"""empty message

Revision ID: 733a57b4e97f
Revises: 194353fba644
Create Date: 2024-03-16 12:58:00.417040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733a57b4e97f'
down_revision = '194353fba644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaxStreak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('CurrentStreak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('CurrentStreak')
        batch_op.drop_column('MaxStreak')

    # ### end Alembic commands ###
